
export const FETCH_LOCATIONS_DETAILS_SUCCESS = 'FETCH_LOCATIONS_DETAILS_SUCCESS';
export const FETCH_LOCATIONS_DETAILS_FAILED = 'FETCH_LOCATIONS_DETAILS_FAILED';
export const FETCH_SERVERS_DETAILS_SUCCESS = 'FETCH_SERVERS_DETAILS_SUCCESS';
export const FETCH_SERVERS_DETAILS_FAILED = 'FETCH_SERVERS_DETAILS_FAILED';
